name: Check Rust News

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  check-rust-news:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Check Rust News
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          BUFFER_API_KEY: ${{ secrets.BUFFER_API_KEY }}
          BUFFER_CHANNEL_ID: ${{ secrets.BUFFER_CHANNEL_ID }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          python src/main.py

      - name: Save news JSON
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add data/latest_news.json data/news_analysis.json data/content_queue.json

          git diff --cached --quiet || git commit -m "Update latest Rust news"

          git push
