name: Check Rust News

on:
  workflow_dispatch:

jobs:
  check-rust-news:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Check Rust News
        run: |
          python src/main.py

      - name: Save news JSON
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add data/latest_news.json

          git diff --cached --quiet || git commit -m "Update latest Rust news"

          git push
